// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservaRestaurante.App.Persistencia;

namespace ReservaRestaurante.App.Persistencia.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ReservaRestaurante.App.Dominio.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .HasColumnType("text");

                    b.Property<int>("cedula")
                        .HasColumnType("int");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("cedula")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ReservaRestaurante.App.Dominio.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("categoria")
                        .HasColumnType("text");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<string>("ubicacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("numero")
                        .IsUnique();

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("ReservaRestaurante.App.Dominio.Mesero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .HasColumnType("text");

                    b.Property<int>("cedula")
                        .HasColumnType("int");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("cedula")
                        .IsUnique();

                    b.ToTable("Meseros");
                });

            modelBuilder.Entity("ReservaRestaurante.App.Dominio.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("clienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime");

                    b.Property<int?>("mesaId")
                        .HasColumnType("int");

                    b.Property<int?>("meseroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("clienteId");

                    b.HasIndex("mesaId");

                    b.HasIndex("meseroId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ReservaRestaurante.App.Dominio.Reserva", b =>
                {
                    b.HasOne("ReservaRestaurante.App.Dominio.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteId");

                    b.HasOne("ReservaRestaurante.App.Dominio.Mesa", "mesa")
                        .WithMany()
                        .HasForeignKey("mesaId");

                    b.HasOne("ReservaRestaurante.App.Dominio.Mesero", "mesero")
                        .WithMany()
                        .HasForeignKey("meseroId");

                    b.Navigation("cliente");

                    b.Navigation("mesa");

                    b.Navigation("mesero");
                });
#pragma warning restore 612, 618
        }
    }
}
