/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package splitandconquer;
import java.util.Arrays;

public class App {
    public void testMerge() {
        MergeSort objMergeSort = new MergeSort();
        int [] par = {3,4,5,8,9,1};
        objMergeSort.sort(par, 0, par.length-1);

        int [] impar = {5,6,9,1,4,3,2};
        objMergeSort.sort(impar, 0, impar.length-1);

        System.out.println(Arrays.toString(par));
        System.out.println(Arrays.toString(impar));
    }

    public void testMinimum() {
        Minimum objMinimum = new Minimum();
        int [] par = {3,4,5,8,9,1};

        int [] impar = {5,6,9,1,4,3,2};

        System.out.println(objMinimum.getMinimum(par, 0, 5));
        System.out.println(objMinimum.getMinimum(impar, 0, 6));
    }
    public void testBinarySearch() {
        BinarySearch objSearch = new BinarySearch();
        int [] par = {1,2,3,4,5,6};

        int [] impar = {2,4,6,8,10,12,14};

        System.out.println(objSearch.search(par, 0, 5, 4));
        System.out.println(objSearch.search(par, 0, 5, 16));

        System.out.println(objSearch.search(impar, 0, 6, 10));
        System.out.println(objSearch.search(impar, 0, 6, 3));

    }


    public static void main(String[] args) {
        App objApp = new App();
        objApp.testMerge();
        objApp.testMinimum();
        objApp.testBinarySearch();
    }
}
