// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketMetro.App.Persistencia;

namespace TicketMetro.App.Persistencia.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210911113404_Cedula")]
    partial class Cedula
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TicketMetro.App.Dominio.Estacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("latitud")
                        .HasColumnType("float");

                    b.Property<double>("longitud")
                        .HasColumnType("float");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Estaciones");
                });

            modelBuilder.Entity("TicketMetro.App.Dominio.Persona", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cedula")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("cedula")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("TicketMetro.App.Dominio.Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("estacionFinalID")
                        .HasColumnType("int");

                    b.Property<int?>("estacionInicialID")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("objPersonaID")
                        .HasColumnType("int");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("estacionFinalID");

                    b.HasIndex("estacionInicialID");

                    b.HasIndex("objPersonaID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketMetro.App.Dominio.Ticket", b =>
                {
                    b.HasOne("TicketMetro.App.Dominio.Estacion", "estacionFinal")
                        .WithMany()
                        .HasForeignKey("estacionFinalID");

                    b.HasOne("TicketMetro.App.Dominio.Estacion", "estacionInicial")
                        .WithMany()
                        .HasForeignKey("estacionInicialID");

                    b.HasOne("TicketMetro.App.Dominio.Persona", "objPersona")
                        .WithMany()
                        .HasForeignKey("objPersonaID");

                    b.Navigation("estacionFinal");

                    b.Navigation("estacionInicial");

                    b.Navigation("objPersona");
                });
#pragma warning restore 612, 618
        }
    }
}
