/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quicksort;
import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        Random rd = new Random(); // creating Random object
        int[] arr = new int[500];
        for (int i = 0; i < arr.length; i++) {
           arr[i] = rd.nextInt(); // storing random integers in an array
        }
        long t1 = System.currentTimeMillis();

        Quicksort objQuicksort = new Quicksort(arr);
        objQuicksort.QuicksortR(1,500);
        long t2 = System.currentTimeMillis();


        int[] arr2 = new int[500];
        for (int i = 0; i < arr2.length; i++) {
           arr2[i] = rd.nextInt(); // storing random integers in an array
        }  
        long t3 = System.currentTimeMillis();        
        Quicksort objQuicksort2 = new Quicksort(arr2);
        objQuicksort2.QuicksortRandom(1, 500);
        long t4 = System.currentTimeMillis();

        System.out.println(
            "Tamaño 500 " +
            "Tiempo normal "+ (t2-t1) +
            " Tiempo random "+ (t4-t3)
        );
        int[] arr3 = new int[1000];
        for (int i = 0; i < arr3.length; i++) {
           arr3[i] = rd.nextInt(); // storing random integers in an array
        }
        t1 = System.currentTimeMillis();
        Quicksort objQuicksort3 = new Quicksort(arr3);
        objQuicksort3.QuicksortR(1,1000);
        t2 = System.currentTimeMillis();

        int[] arr4 = new int[1000];
        for (int i = 0; i < arr4.length; i++) {
           arr4[i] = rd.nextInt(); // storing random integers in an array
        }

        t3 = System.currentTimeMillis();
        Quicksort objQuicksort4 = new Quicksort(arr4);
        objQuicksort4.QuicksortRandom(1, 1000);
        t4 = System.currentTimeMillis();
        System.out.println(
            "Tamaño 1000 " +
            "Tiempo normal "+ (t2-t1) +
            " Tiempo random "+ (t4-t3)
        );

    }
}
