if (self.CavalryLogger) { CavalryLogger.start_js(["HvCV\/"]); }

__d("CometGroupAboutRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3017286228370074",metadata:{relayPreloadable:!0},name:"CometGroupAboutRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGroupAnnouncementsRootFeedQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3061378403917473",metadata:{relayPreloadable:!0},name:"CometGroupAnnouncementsRootFeedQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGroupEventsRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3160198170714497",metadata:{relayPreloadable:!0},name:"CometGroupEventsRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometFilesTabRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2957181401027544",metadata:{relayPreloadable:!0},name:"GroupsCometFilesTabRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometJVCRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3576389825711425",metadata:{relayPreloadable:!0},name:"GroupsCometJVCRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometPhotosRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3840994309275731",metadata:{relayPreloadable:!0},name:"GroupsCometPhotosRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGroupMembersRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4075388579200974",metadata:{relayPreloadable:!0},name:"CometGroupMembersRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGroupAboutRoot.entrypoint",["JSResource","WebPixelRatio","buildGroupCometRoot.entrypoint","CometGroupAboutRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildGroupCometRoot.entrypoint")(b("JSResource")("CometGroupAboutRoot.react").__setRef("CometGroupAboutRoot.entrypoint"),function(a){a=a.routeProps;a=a.groupID;return{queries:{aboutQueryReference:{parameters:b("CometGroupAboutRootQuery$Parameters"),variables:{groupID:a,scale:b("WebPixelRatio").get()}}}}});e.exports=a}),null);
__d("CometGroupAnnouncementsRoot.entrypoint",["JSResource","WebPixelRatio","buildGroupCometRoot.entrypoint","CometGroupAnnouncementsRootFeedQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildGroupCometRoot.entrypoint")(b("JSResource")("CometGroupAnnouncementsRoot.react").__setRef("CometGroupAnnouncementsRoot.entrypoint"),function(a){a=a.routeProps;a=a.groupID;a={feedLocation:"GROUP_ANNOUNCEMENTS_FEED",feedbackSource:0,focusCommentID:null,groupID:a,isComet:!0,privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"group",scale:b("WebPixelRatio").get()};return{queries:{queryReference:{parameters:b("CometGroupAnnouncementsRootFeedQuery$Parameters"),variables:a}}}});e.exports=a}),null);
__d("CometGroupEventsRoot.entrypoint",["JSResource","WebPixelRatio","buildGroupCometRoot.entrypoint","CometGroupEventsRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";var g=3;a=b("buildGroupCometRoot.entrypoint")(b("JSResource")("CometGroupEventsRoot.react").__setRef("CometGroupEventsRoot.entrypoint"),function(a){a=a.routeProps;a=a.groupID;a={count:g,groupID:a,scale:b("WebPixelRatio").get()};return{queries:{queryReference:{parameters:b("CometGroupEventsRootQuery$Parameters"),variables:a}}}});e.exports=a}),null);
__d("GroupsCometFilesTabRoot.entrypoint",["JSResource","buildGroupCometRoot.entrypoint","GroupsCometFilesTabRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildGroupCometRoot.entrypoint")(b("JSResource")("GroupsCometFilesTabRoot.react").__setRef("GroupsCometFilesTabRoot.entrypoint"),function(a){a=a.routeProps;a=a.groupID;return{queries:{queryReference:{parameters:b("GroupsCometFilesTabRootQuery$Parameters"),variables:{groupID:a}}}}});e.exports=a}),null);
__d("GroupsCometJVCRoot.entrypoint",["JSResource","buildGroupCometRoot.entrypoint","GroupsCometJVCRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildGroupCometRoot.entrypoint")(b("JSResource")("GroupsCometJVCRoot.react").__setRef("GroupsCometJVCRoot.entrypoint"),function(a){a=a.routeProps.groupID;a={groupID:a};return{queries:{queryReference:{parameters:b("GroupsCometJVCRootQuery$Parameters"),variables:a}}}});e.exports=a}),null);
__d("GroupsCometPhotosRootQueryVariables",[],(function(a,b,c,d,e,f){"use strict";a=8;f.count=a}),null);
__d("GroupsCometPhotosRoot.entrypoint",["GroupsCometPhotosRootQueryVariables","JSResource","WebPixelRatio","buildGroupCometRoot.entrypoint","GroupsCometPhotosRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildGroupCometRoot.entrypoint")(b("JSResource")("GroupsCometPhotosRoot.react").__setRef("GroupsCometPhotosRoot.entrypoint"),function(a){a=a.routeProps.groupID;return{queries:{queryReference:{parameters:b("GroupsCometPhotosRootQuery$Parameters"),variables:babelHelpers["extends"]({groupID:a,scale:b("WebPixelRatio").get()},b("GroupsCometPhotosRootQueryVariables"))}}}});e.exports=a}),null);
__d("CometGroupMembersRoot.entrypoint",["JSResource","WebPixelRatio","buildGroupCometRoot.entrypoint","CometGroupMembersRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildGroupCometRoot.entrypoint")(b("JSResource")("CometGroupMembersRoot.react").__setRef("CometGroupMembersRoot.entrypoint"),function(a){a=a.routeProps;a=a.groupID;a={groupID:a,scale:b("WebPixelRatio").get()};return{queries:{queryReference:{parameters:b("CometGroupMembersRootQuery$Parameters"),variables:a}}}});e.exports=a}),null);