if (self.CavalryLogger) { CavalryLogger.start_js(["jbMKX"]); }

__d("CometVideoHomeCatalogRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3160352010674823",metadata:{relayPreloadable:!0},name:"CometVideoHomeCatalogRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeInjectedLiveVideoQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3488418321191249",metadata:{relayPreloadable:!0},name:"CometVideoHomeInjectedLiveVideoQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeLiveRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3415899071775242",metadata:{relayPreloadable:!0},name:"CometVideoHomeLiveRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeSavedRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3242005662488296",metadata:{relayPreloadable:!0},name:"CometVideoHomeSavedRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeCatalogRoot.entrypoint",["JSResource","WebPixelRatio","buildCometVideoHomeRoute.entrypoint","qex","CometVideoHomeCatalogRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeCatalogRoot.react").__setRef("CometVideoHomeCatalogRoot.entrypoint"),function(a){return{queries:{catalogRootQueryReference:{parameters:b("CometVideoHomeCatalogRootQuery$Parameters"),variables:{feedHeroEnabled:!!b("qex")._("1418988"),scale:b("WebPixelRatio").get()}}}}});e.exports=a}),null);
__d("CometVideoHomeLiveEntryPointVariables",["WebPixelRatio","gkx","qex"],(function(a,b,c,d,e,f){"use strict";c={scale:b("WebPixelRatio").get(),useCometLiveEndedOverlay:(a=b("gkx"))("1362110")};d={feedLocation:"VIDEO_HOME_LIVE_TAB",feedbackSource:60,isComet:a("708253"),isCommunityViewEntryPointEnabled:!!b("qex")._("1571809"),removeRealtimeUFI:a("1344274"),shareSheetRedesign:a("1365892")};f.CometVideoHomeLiveHeroUFIEntryPointVariables=d;e=babelHelpers["extends"]({},c,{isComet:a("708253")});f.CometVideoHomeLiveHeroEntryPointVariables=e;e=babelHelpers["extends"]({},c,d,{openInPageLiveTab:!!b("qex")._("1611011"),skipGridComponentAttachedStory:a("1454794"),useThumbnailPreviewRelay3d:a("1357994")});f.CometVideoHomeLiveRootEntryPointVariables=e}),null);
__d("CometVideoHomeInjectedLiveVideo.entrypoint",["CometVideoHomeLiveEntryPointVariables","JSResource","CometVideoHomeInjectedLiveVideoQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){a=babelHelpers["extends"]({},b("CometVideoHomeLiveEntryPointVariables").CometVideoHomeLiveHeroEntryPointVariables,b("CometVideoHomeLiveEntryPointVariables").CometVideoHomeLiveHeroUFIEntryPointVariables,{videoID:(a=a.routeProps.v)!=null?a:""});return{queries:{injectedLiveVideoQueryReference:{parameters:b("CometVideoHomeInjectedLiveVideoQuery$Parameters"),variables:a}}}},root:b("JSResource")("CometVideoHomeInjectedLiveVideo.react").__setRef("CometVideoHomeInjectedLiveVideo.entrypoint")};e.exports=a}),null);
__d("CometVideoHomeLiveRootEntrypoint.entrypoint",["CometVideoHomeLiveEntryPointVariables","JSResource","CometVideoHomeLiveRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){return{queries:{liveRootQueryReference:{parameters:b("CometVideoHomeLiveRootQuery$Parameters"),variables:babelHelpers["extends"]({},b("CometVideoHomeLiveEntryPointVariables").CometVideoHomeLiveRootEntryPointVariables,{trigger_data:{injected_video_id:a.routeProps.v}})}}}},root:b("JSResource")("CometVideoHomeLiveRoot.react").__setRef("CometVideoHomeLiveRootEntrypoint.entrypoint")};e.exports=a}),null);
__d("CometVideoHomeLiveInjectionRoot.entrypoint",["JSResource","buildCometVideoHomeRoute.entrypoint","CometVideoHomeInjectedLiveVideo.entrypoint","CometVideoHomeLiveRootEntrypoint.entrypoint"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeLiveInjectionRoot.react").__setRef("CometVideoHomeLiveInjectionRoot.entrypoint"),function(a){return{entryPoints:{injectedLiveVideoNestedEntryPoint:{entryPoint:b("CometVideoHomeInjectedLiveVideo.entrypoint"),entryPointParams:a},liveRootNestedEntryPoint:{entryPoint:b("CometVideoHomeLiveRootEntrypoint.entrypoint"),entryPointParams:a}},extraProps:{externalLogID:a.routeProps.externalLogID,t:a.routeProps.t}}});e.exports=a}),null);
__d("CometVideoHomeLiveRoot.entrypoint",["CometVideoHomeLiveEntryPointVariables","JSResource","buildCometVideoHomeRoute.entrypoint","CometVideoHomeLiveRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeLiveRoot.react").__setRef("CometVideoHomeLiveRoot.entrypoint"),function(a){return{queries:{liveRootQueryReference:{parameters:b("CometVideoHomeLiveRootQuery$Parameters"),variables:babelHelpers["extends"]({},b("CometVideoHomeLiveEntryPointVariables").CometVideoHomeLiveRootEntryPointVariables,{trigger_data:{injected_video_id:null}})}}}});e.exports=a}),null);
__d("CometVideoHomeSavedRoot.entrypoint",["JSResource","WebPixelRatio","buildCometVideoHomeRoute.entrypoint","qex","CometVideoHomeSavedRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeSavedRoot.react").__setRef("CometVideoHomeSavedRoot.entrypoint"),function(a){return{queries:{savedRootQueryReference:{parameters:b("CometVideoHomeSavedRootQuery$Parameters"),variables:{feedHeroEnabled:!!b("qex")._("1418988"),scale:b("WebPixelRatio").get()}}}}});e.exports=a}),null);