if (self.CavalryLogger) { CavalryLogger.start_js(["cJrf6"]); }

__d("CoronavirusCometRootContentQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2852350711551507",metadata:{relayPreloadable:!0},name:"CoronavirusCometRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CoronavirusHubCometRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2793253620780661",metadata:{relayPreloadable:!0},name:"CoronavirusHubCometRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CoronavirusCometHeaderQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3308342189184240",metadata:{relayPreloadable:!0},name:"CoronavirusCometHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("FundraiserHubLeftRailSectionsQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4117371904970497",metadata:{relayPreloadable:!0},name:"FundraiserHubLeftRailSectionsQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PageCometLaunchpointLeftNavMenuRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3111637862248632",metadata:{relayPreloadable:!0},name:"PageCometLaunchpointLeftNavMenuRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PageCometLaunchpointPagesListQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3175270202587950",metadata:{relayPreloadable:!0},name:"PageCometLaunchpointPagesListQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("buildCoronavirusCometRoot.entrypoint",["JSResource","createContentAreaCompoundEntryPointBuilder","CoronavirusCometRootContentQuery$Parameters","CoronavirusCometHeaderQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("CoronavirusCometRoot.react").__setRef("buildCoronavirusCometRoot.entrypoint"),function(a){return{crisisQueryReference:{parameters:b("CoronavirusCometRootContentQuery$Parameters"),variables:{}},headerQueryReference:{parameters:b("CoronavirusCometHeaderQuery$Parameters"),variables:{}}}});e.exports=a}),null);
__d("CoronavirusHubCometRoot.entrypoint",["JSResource","WebPixelRatio","buildCoronavirusCometRoot.entrypoint","CoronavirusHubCometRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildCoronavirusCometRoot.entrypoint")(b("JSResource")("CoronavirusHubCometRoot.react").__setRef("CoronavirusHubCometRoot.entrypoint"),function(a){a=a.routeParams.hoisted_content_id;return{queries:{queryReference:{parameters:b("CoronavirusHubCometRootQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"CoronavirusHubCometRootQuery",displayCommentsContextEnableComment:!0,displayCommentsContextIsAdPreview:!1,displayCommentsContextIsAggregatedShare:!1,displayCommentsContextIsStorySet:!1,displayCommentsFeedbackContext:null,feedLocation:"COMET_CORONAVIRUS_HUB_FEED",feedbackSource:22,focusCommentID:null,hoistedContentID:a,isComet:!0,privacySelectorRenderLocation:"COMET_CORONAVIRUS_HUB",renderLocation:"coronavirus_hub_feed",scale:b("WebPixelRatio").get(),useDefaultActor:!1}}}}});e.exports=a}),null);
__d("buildCometFundraiserHubRoute.entrypoint",["JSResource","WebPixelRatio","createContentAreaCompoundEntryPointBuilder","FundraiserHubLeftRailSectionsQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("FundraiserHubRoot.react").__setRef("buildCometFundraiserHubRoute.entrypoint"),function(a){return{leftRailSectionsQueryReference:{parameters:b("FundraiserHubLeftRailSectionsQuery$Parameters"),variables:{scale:b("WebPixelRatio").get()}}}});e.exports=a}),null);
__d("buildPageCometLaunchpointRoute.entrypoint",["JSResource","createContentAreaCompoundEntryPointBuilder","gkx","PageCometLaunchpointLeftNavMenuRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("PageCometLaunchpointEntryPointRoot.react").__setRef("buildPageCometLaunchpointRoute.entrypoint"),function(a){return{leftNavContainerQueryReference:{parameters:b("PageCometLaunchpointLeftNavMenuRootQuery$Parameters"),variables:{inNewPageSignPostExperiment:b("gkx")("1595283"),useNewPagesYouManage:b("gkx")("1549707")}}}});e.exports=a}),null);
__d("PageCometLaunchpointFullPageEntryPointCompatRoot.entrypoint",["JSResource","buildPageCometLaunchpointRoute.entrypoint"],(function(a,b,c,d,e,f){"use strict";a=b("buildPageCometLaunchpointRoute.entrypoint")(b("JSResource")("CometFullPageEntryPointCompatRoot.react").__setRef("PageCometLaunchpointFullPageEntryPointCompatRoot.entrypoint"),function(a){a=a.routeProps.maintainKey;return{extraProps:{routeProps:{maintainKey:a}}}});e.exports=a}),null);
__d("PageCometLaunchpointPagesList.entrypoint",["JSResource","WebPixelRatio","buildPageCometLaunchpointRoute.entrypoint","gkx","PageCometLaunchpointPagesListQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildPageCometLaunchpointRoute.entrypoint")(b("JSResource")("PageCometLaunchpointPagesList.react").__setRef("PageCometLaunchpointPagesList.entrypoint"),function(a){return{queries:{pageCometLaunchpointPagesListQueryReference:{parameters:b("PageCometLaunchpointPagesListQuery$Parameters"),variables:{inNewPageSignPostExperiment:b("gkx")("1595283"),scale:b("WebPixelRatio").get()}}}}});e.exports=a}),null);