if (self.CavalryLogger) { CavalryLogger.start_js(["Vh5Fk"]); }

__d("EventCometDiscussionCardRendererQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3075926112443790",metadata:{relayPreloadable:!0},name:"EventCometDiscussionCardRendererQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometPermalinkHeaderQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3117420685010470",metadata:{relayPreloadable:!0},name:"EventCometPermalinkHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PrivateEventCometTabQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3103039126445986",metadata:{relayPreloadable:!0},name:"PrivateEventCometTabQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PublicEventCometAboutRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3540852262599873",metadata:{relayPreloadable:!0},name:"PublicEventCometAboutRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PublicEventCometDiscussionRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4157733097631900",metadata:{relayPreloadable:!0},name:"PublicEventCometDiscussionRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometFeedVariables",["WebPixelRatio"],(function(a,b,c,d,e,f){"use strict";f.getFeedVariables=a;function a(a,c,d,e){return{displayCommentsContextEnableComment:null,displayCommentsContextIsAdPreview:null,displayCommentsContextIsAggregatedShare:null,displayCommentsContextIsStorySet:null,displayCommentsFeedbackContext:null,eventID:a,feedLocation:"EVENT",feedbackSource:34,focusCommentID:(a=e)!=null?a:d,hoistedIDs:(e=c)!=null?e:[],isComet:!0,privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"event",scale:b("WebPixelRatio").get(),useDefaultActor:!1}}}),null);
__d("PrivateEventCometRoot.entrypoint",["EventCometFeedVariables","JSResource","WebPixelRatio","EventCometDiscussionCardRendererQuery$Parameters","EventCometPermalinkHeaderQuery$Parameters","PrivateEventCometTabQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";var g=7771;a={getPreloadProps:function(a){var c=a.routeParams,d=c.comment_id;c=c.reply_comment_id;a=a.routeProps;var e=a.eventID;a=a.postIDs;var f=b("WebPixelRatio").get(),h=g;return{queries:{eventDiscussionCardRendererQueryReference:{parameters:b("EventCometDiscussionCardRendererQuery$Parameters"),variables:b("EventCometFeedVariables").getFeedVariables(e,a,d,c)},eventPermalinkHeaderQueryReference:{parameters:b("EventCometPermalinkHeaderQuery$Parameters"),variables:{eventID:e,scale:f}},privateEventTabQueryReference:{parameters:b("PrivateEventCometTabQuery$Parameters"),variables:{eventID:e,nuxID:h,scale:f}}}}},root:b("JSResource")("PrivateEventCometRoot.react").__setRef("PrivateEventCometRoot.entrypoint")};e.exports=a}),null);
__d("buildPublicEventCometRoute.entrypoint",["JSResource","WebPixelRatio","createContentAreaCompoundEntryPointBuilder","EventCometPermalinkHeaderQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("PublicEventCometRoot.react").__setRef("buildPublicEventCometRoute.entrypoint"),function(a){a=a.routeProps;a=a.eventID;var c=b("WebPixelRatio").get();return{eventPermalinkHeaderQueryReference:{parameters:b("EventCometPermalinkHeaderQuery$Parameters"),variables:{eventID:a,scale:c}}}});e.exports=a}),null);
__d("PublicEventCometAboutRoot.entrypoint",["JSResource","WebPixelRatio","buildPublicEventCometRoute.entrypoint","PublicEventCometAboutRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";var g=7771;a=b("buildPublicEventCometRoute.entrypoint")(b("JSResource")("PublicEventCometAboutRoot.react").__setRef("PublicEventCometAboutRoot.entrypoint"),function(a){a=a.routeProps;a=a.eventID;var c=g,d=b("WebPixelRatio").get();return{queries:{publicEventAboutRootQueryReference:{parameters:b("PublicEventCometAboutRootQuery$Parameters"),variables:{eventID:a,nuxID:c,scale:d}}}}});e.exports=a}),null);
__d("PublicEventCometDiscussionRoot.entrypoint",["EventCometFeedVariables","JSResource","WebPixelRatio","buildPublicEventCometRoute.entrypoint","EventCometDiscussionCardRendererQuery$Parameters","PublicEventCometDiscussionRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildPublicEventCometRoute.entrypoint")(b("JSResource")("PublicEventCometDiscussionRoot.react").__setRef("PublicEventCometDiscussionRoot.entrypoint"),function(a){var c=a.routeParams;a=a.routeProps;var d=a.eventID;a=a.postIDs;var e=b("WebPixelRatio").get(),f=c.comment_id;c=c.reply_comment_id;return{queries:{eventDiscussionCardRendererQueryReference:{parameters:b("EventCometDiscussionCardRendererQuery$Parameters"),variables:b("EventCometFeedVariables").getFeedVariables(d,a,f,c)},publicEventDiscussionRootQueryReference:{parameters:b("PublicEventCometDiscussionRootQuery$Parameters"),variables:{eventID:d,scale:e}}}}});e.exports=a}),null);