if (self.CavalryLogger) { CavalryLogger.start_js(["YEROL"]); }

__d("XCometVanityURLControllerRouteBuilder",["cometRouteBuilder"],(function(a,b,c,d,e,f){a=b("cometRouteBuilder")("/{vanity}/",Object.freeze({}),void 0);e.exports=a}),null);
__d("CometDismissFBNuxMutation.graphql",[],(function(a,b,c,d,e,f){"use strict";a=function(){var a=[{defaultValue:null,kind:"LocalArgument",name:"nux_id_input"}],b=[{kind:"Variable",name:"nux_id",variableName:"nux_id_input"}],c={alias:null,args:null,kind:"ScalarField",name:"should_show",storageKey:null};return{fragment:{argumentDefinitions:a,kind:"Fragment",metadata:null,name:"CometDismissFBNuxMutation",selections:[{alias:null,args:b,concreteType:null,kind:"LinkedField",name:"nux_dismiss",plural:!1,selections:[c],storageKey:null}],type:"Mutation",abstractKey:null},kind:"Request",operation:{argumentDefinitions:a,kind:"Operation",name:"CometDismissFBNuxMutation",selections:[{alias:null,args:b,concreteType:null,kind:"LinkedField",name:"nux_dismiss",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},c,{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null}]},params:{id:"2684807914920359",metadata:{},name:"CometDismissFBNuxMutation",operationKind:"mutation",text:null}}}();e.exports=a}),null);
__d("CometLogImpressionFBNuxMutation.graphql",[],(function(a,b,c,d,e,f){"use strict";a=function(){var a=[{defaultValue:null,kind:"LocalArgument",name:"nux_id"}],b=[{kind:"Variable",name:"nux_id",variableName:"nux_id"}],c={alias:null,args:null,kind:"ScalarField",name:"nux_id",storageKey:null};return{fragment:{argumentDefinitions:a,kind:"Fragment",metadata:null,name:"CometLogImpressionFBNuxMutation",selections:[{alias:null,args:b,concreteType:null,kind:"LinkedField",name:"log_nux_view",plural:!1,selections:[c],storageKey:null}],type:"Mutation",abstractKey:null},kind:"Request",operation:{argumentDefinitions:a,kind:"Operation",name:"CometLogImpressionFBNuxMutation",selections:[{alias:null,args:b,concreteType:null,kind:"LinkedField",name:"log_nux_view",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},c,{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null}]},params:{id:"3161132830580128",metadata:{},name:"CometLogImpressionFBNuxMutation",operationKind:"mutation",text:null}}}();e.exports=a}),null);
__d("useProfileCometSwitcherCleanUpOnSwap_query.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useProfileCometSwitcherCleanUpOnSwap_query",selections:[{alias:null,args:null,kind:"ScalarField",name:"logout_whitelist",storageKey:null}],type:"Query",abstractKey:null};e.exports=a}),null);
__d("ProfileCometLifeEventsComposerDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3095717357164554",metadata:{relayPreloadable:!0},name:"ProfileCometLifeEventsComposerDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("MWChatUpdateMuteSettingMutation.graphql",[],(function(a,b,c,d,e,f){"use strict";a=function(){var a=[{defaultValue:null,kind:"LocalArgument",name:"input"}],b=[{alias:null,args:[{kind:"Variable",name:"data",variableName:"input"}],concreteType:"MessengerUpdateMuteSettingResponsePayload",kind:"LinkedField",name:"messenger_update_mute_setting",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"muted_until",storageKey:null}],storageKey:null}];return{fragment:{argumentDefinitions:a,kind:"Fragment",metadata:null,name:"MWChatUpdateMuteSettingMutation",selections:b,type:"Mutation",abstractKey:null},kind:"Request",operation:{argumentDefinitions:a,kind:"Operation",name:"MWChatUpdateMuteSettingMutation",selections:b},params:{id:"2376670165755701",metadata:{},name:"MWChatUpdateMuteSettingMutation",operationKind:"mutation",text:null}}}();e.exports=a}),null);
__d("encodeNUXIDForRelay",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g="NUX_ID:";function a(a){return typeof a==="string"&&a.startsWith(g)?{nuxID:Number(a.replace(g,"")),relayID:a}:{nuxID:Number(a),relayID:g+a}}}),null);
__d("CometDismissFBNuxMutation",["CometRelay","encodeNUXIDForRelay","CometDismissFBNuxMutation.graphql"],(function(a,b,c,d,e,f){"use strict";f.commit=a;var g,h=g!==void 0?g:g=b("CometDismissFBNuxMutation.graphql");function a(a,c,d,e){c=b("encodeNUXIDForRelay")(c);var f=c.nuxID;c=c.relayID;return b("CometRelay").commitMutation(a,{mutation:h,onCompleted:d,onError:e,optimisticResponse:{nux_dismiss:{__typename:"NUX",id:c,should_show:!1}},variables:{nux_id_input:f}})}}),null);
__d("CometLogImpressionFBNuxMutation",["CometRelay","encodeNUXIDForRelay","CometLogImpressionFBNuxMutation.graphql"],(function(a,b,c,d,e,f){"use strict";f.commit=a;var g,h=g!==void 0?g:g=b("CometLogImpressionFBNuxMutation.graphql");function a(a,c,d,e){c=b("encodeNUXIDForRelay")(c);c=c.nuxID;return b("CometRelay").commitMutation(a,{mutation:h,onCompleted:d,onError:e,variables:{nux_id:c}})}}),null);
__d("useCometTriggerOptOut",["Promise","CometTrialParticipationChangeMutation","recoverableViolation","requireCond","cr:1391111"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1391111")({onOptOut:function(a){return new(b("Promise"))(function(c,d){b("CometTrialParticipationChangeMutation").commit(a,{change_type:"OPT_OUT",source:"SETTINGS_MENU"},function(a){((a=a.comet_trial_participation_change)==null?void 0:a.success)===!0?c():d("result.success is not true")},d)})},onOptOutCompleted:function(){window.location.reload()},onOptOutError:function(a){b("recoverableViolation")("Error when trying to opt out of Comet: "+a.toString(),"comet_ui")}});e.exports=a}),null);
__d("useProfileCometSwitcherCleanUpOnSwap",["Banzai","CometRelay","React","ServiceWorkerLoginAndLogout","WebStorageMonster","useProfileCometSwitcherCleanUpOnSwap_query.graphql"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=b("React");function a(a){a=b("CometRelay").useFragment(g!==void 0?g:g=b("useProfileCometSwitcherCleanUpOnSwap_query.graphql"),a);var c=a.logout_whitelist;return h.useCallback(function(){b("WebStorageMonster").cleanOnLogout(c),b("ServiceWorkerLoginAndLogout").logout(),b("Banzai").flush()},[c])}}),null);
__d("ProfileCometLifeEventsComposerDialog.entrypoint",["JSResource","WebPixelRatio","ProfileCometLifeEventsComposerDialogQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){return{queries:{queryReference:{parameters:b("ProfileCometLifeEventsComposerDialogQuery$Parameters"),variables:{scale:b("WebPixelRatio").get()}}}}},root:b("JSResource")("ProfileCometLifeEventsComposerDialog.react").__setRef("ProfileCometLifeEventsComposerDialog.entrypoint")};e.exports=a}),null);
__d("useLifeEventsComposerDialog",["fbt","CometCardedDialogLoadingState.react","ProfileCometLifeEventsComposerDialog.entrypoint","React","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";e.exports=a;var h=b("React");function i(){return h.jsx(b("CometCardedDialogLoadingState.react"),{title:g._("Create life event")})}function a(a){var c=b("useCometEntryPointDialog")(b("ProfileCometLifeEventsComposerDialog.entrypoint"),{},"button",function(){return h.jsx(i,{})}),d=c[0],e=c[1],f=c[2],g=c[3];c=c[4];return[h.useCallback(function(){d({surface:a})},[d,a]),e,f,g,c]}}),null);
__d("MWChatUpdateMuteSettingMutation",["CometRelay","CometRelayEnvironment","createCommitMutation","MWChatUpdateMuteSettingMutation.graphql"],(function(a,b,c,d,e,f){"use strict";var g;a=b("createCommitMutation").createCommitMutation(b("CometRelayEnvironment"),{mutation:g!==void 0?g:g=b("MWChatUpdateMuteSettingMutation.graphql")});f.commit=a}),null);
__d("MessengerMuteUtils.bs",["fbt","formatDate","DateStrings"],(function(a,b,c,d,e,f,g){"use strict";function a(a){if(a>0)if(a<86401)return;else{var c=new Date(a*1e3).getDay(),d=c===new Date().getDay(),e=c===new Date().getDay()+1;if(e)return g._("Off until {time} tomorrow",[g._param("time",b("formatDate")(a,"g:ia"))]);else if(d)return g._("Off until {time}",[g._param("time",b("formatDate")(a,"g:ia"))]);else return g._("Off until {time} on {weekday name}",[g._param("time",b("formatDate")(a,"g:ia")),g._param("weekday name",b("DateStrings").getWeekdayName(c))])}else if(a===-1)return g._("Off indefinitely");else return}function c(a,b){if(a)if(b)return g._("Unmute notifications");else return g._("Mute notifications");else if(b)return g._("Unmute conversation");else return g._("Mute conversation")}f.mutedUntilLabel=a;f.muteActionLabel=c}),null);
__d("MWChatSearchTypeaheadDataEntry",[],(function(a,b,c,d,e,f){"use strict";a=function(){function a(a){this.$1=a}var b=a.prototype;b.getKey=function(){return this.$1.id};b.getLabel=function(){return this.$1.displayName};b.getMetaData=function(){return this.$2};b.getRawData=function(){return this.$1};b.getResultType=function(){return this.$1.resultType};b.setMetaData=function(a){this.$2=a;return this};return a}();e.exports=a}),null);
__d("MessengerMQTTPresence",["BanzaiODS","FBMqttChannel"],(function(a,b,c,d,e,f){"use strict";var g="/orca_presence",h="mqtt_web.presence",i="/send_additional_contacts",j=!1;a={subscribe:function(a){if(j)return;j=!0;b("FBMqttChannel").subscribe(g,function(c){c=JSON.parse(c);c&&c.list&&(c.list_type&&c.list_type==="full"&&a.reset(),a.setMultiFromMQTT(c.list),b("BanzaiODS").bumpEntityKey(3303,h,"buddylist.event"),b("BanzaiODS").bumpEntityKey(3303,h,"buddylist.active_buddies",c.list.length))})},unsubscribe:function(){j=!1,b("FBMqttChannel").unsubscribeAll(g)},sendAdditionalBuddyRequest:function(a){b("FBMqttChannel").publish(i,JSON.stringify({additional_contacts:[a]}))}};e.exports=a}),null);
__d("RelayFBEnvironmentFactory",["RelayModern"],(function(a,b,c,d,e,f){"use strict";a=b("RelayModern").createEnvironmentFactory;e.exports=a(function(a){return{configName:"RelayFBEnvironment",actorID:a}})}),null);
__d("RelayFBDefaultEnvironment",["RelayFBEnvironmentFactory"],(function(a,b,c,d,e,f){"use strict";e.exports=b("RelayFBEnvironmentFactory").getForActorID(null)}),null);